flowchart TD
    D[DRAFT] --> RF[SCANNING_RELEVANT_FILES]
    RF --> ID[COUNCIL_DELIBERATING]
    ID --> IV[COUNCIL_VOTING_INTERVIEW]
    IV --> IC[COMPILING_INTERVIEW]
    IC --> IQ[WAITING_INTERVIEW_ANSWERS]
    IQ --> ICV[VERIFYING_INTERVIEW_COVERAGE]
    ICV --> IA[WAITING_INTERVIEW_APPROVAL]
    IA --> PD[DRAFTING_PRD]
    PD --> PV[COUNCIL_VOTING_PRD]
    PV --> PR[REFINING_PRD]
    PR --> PC[VERIFYING_PRD_COVERAGE]
    PC --> PA[WAITING_PRD_APPROVAL]
    PA --> BD[DRAFTING_BEADS]
    BD --> BV[COUNCIL_VOTING_BEADS]
    BV --> BR[REFINING_BEADS]
    BR --> BC[VERIFYING_BEADS_COVERAGE]
    BC --> BE[EXPANDING_BEADS]
    BE --> BA[WAITING_BEADS_APPROVAL]
    BA --> PF[PRE_FLIGHT_CHECK]
    PF --> ESG[GENERATING_EXECUTION_SETUP_PLAN]
    ESG --> ESA[WAITING_EXECUTION_SETUP_APPROVAL]
    ESA --> EE[PREPARING_EXECUTION_ENV]
    EE --> C[CODING]
    C --> FT[RUNNING_FINAL_TEST]
    FT --> QAG[GENERATING_QA_CHECKLIST]
    QAG --> QA[WAITING_MANUAL_QA]
    QA --> IN[INTEGRATING_CHANGES]
    QA -. failed checks .-> C
    FT -. Manual QA disabled .-> IN
    IN --> PRC[CREATING_PULL_REQUEST]
    PRC --> PRR[WAITING_PR_REVIEW]
    PRR --> CL[CLEANING_ENV]
    CL --> DONE[COMPLETED]

    ERR[BLOCKED_ERROR] -. retry or eligible continue .-> RET[PREVIOUS_STATUS]
    RET -. resume .-> RF
    ACTIVE[Any active non-terminal phase] -. operational failure .-> ERR
    ACTIVE -. cancel .-> CANCEL[CANCELED]
